### ISSUE TITLE
Working on the policy side

### ISSUE THREAD

**Issue by josueeek** [flyve-mdm/web-mdm-dashboard#1138]
Hi, 

I am having problems in this code snippet, it is not working on the policy side.

```JS
const policyType = policy['PluginFlyvemdmPolicy.type']
    // Check if the policy default value are applications, files or other
    switch (policyType) {
      case 'deployapp':
      case 'removeapp':
        return data.applications
      case 'deployfile':
      case 'removefile':
        return data.files
      case 'dropdown':
        return Object.entries(JSON.parse(policy['PluginFlyvemdmPolicy.type_data']))
      default:
        return JSON.parse(policy['PluginFlyvemdmPolicy.type_data'])
    }
  }
```
![captura de tela 2018-10-23 as 15 15 11](https://user-images.githubusercontent.com/28680407/47384187-c8835700-d6dc-11e8-92ad-23e41df1d615.png)

**Comment by Gianfranco97** [comment]
Sorry I am not able to reproduce this problem. Both for the dev server and the demo server is working correctly.

![demo-dashboard flyve org_app_devices_26 1](https://user-images.githubusercontent.com/19965590/47661849-3c57b080-db70-11e8-97c2-98438e621af5.png)


Please, clearly specify the steps to follow in order to reproduce the error.
