### ISSUE TITLE
Documentation on the CI fails

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#1141]
Hi, @Naylin15 

Documentation on the CI fails:

https://circleci.com/gh/flyve-mdm/web-mdm-dashboard/6112?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```console
$ yarn jsdoc src -r -d docs -t ./jsdoc_theme
$ /root/flyve/node_modules/.bin/jsdoc src -r -d docs -t ./jsdoc_theme
```

**Comment by Naylin15** [comment]
Regarding the coverage, I'm not sure what could be causing the error when running the script from SSH in my fork it pass 

![captura de pantalla 2018-11-15 a la s 4 35 20 p m](https://user-images.githubusercontent.com/30867977/48580100-a4d6b980-e8f4-11e8-9e3a-98342e603307.png)

**Comment by Naylin15** [comment]
Hi @ajsb85 @Gianfranco97 

The coverage is failing now due to wrong credentials in the CI configuration, I'll be chaging them from Flyve MDM to Teclib'

![captura de pantalla 2018-11-16 a la s 4 26 37 p m](https://user-images.githubusercontent.com/30867977/48646176-758c7f00-e9be-11e8-9372-47509e71aade.png)

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Generate documentation on CircleCI.

Reference:
https://circleci.com/gh/flyve-mdm/web-mdm-dashboard/6459?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
