### ISSUE TITLE
Error in Help Center

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/web-mdm-dashboard#937]
**Describe the bug**
When selecting the option help center it shows a message error and do not load the articles

**To Reproduce**
1. Go to About section
2. Click on Help center
3. See error

**Expected behavior**

No error and browse the existing articles

**Screenshots**
![captura de pantalla 2018-07-04 a la s 12 13 45 p m](https://user-images.githubusercontent.com/30867977/42287541-afd414f6-7f84-11e8-92c5-eca502b6d7a7.png)

**Desktop (please complete the following information):**
 - OS: Mac 10.13.5
 - Browser: Chrome

**Additional context**
My user is Super Admin (R), root entiy
There are existing articles in the knowledge base

![captura de pantalla 2018-07-04 a la s 12 22 19 p m](https://user-images.githubusercontent.com/30867977/42287605-f91101c4-7f84-11e8-808c-aa18edc789eb.png)

**Comment by Gianfranco97** [comment]
I was reviewing and doing several tests. It turns out that the problem has to do with the type of user, certainly the user with whom he was doing tests is a super user, but the problem is that it was of the recursive type. It turns out that glpi does not allow these types of users to search, which causes the requests used on that screen to stop working.

**Comment by Gianfranco97** [comment]
Not being able to do search is a big problem, because although it is true that I have permission to request data through a getAllItems, the truth is that I have no way of knowing how many elements exist in total, making it impossible to use correctly Lean parameter and by default the getAllItems endpoint only brings the first 15 matches.
